create table if not exists public.matchmaking_queue (
    id bigint generated by default as identity primary key,
    player_id text not null,
    status text not null default 'waiting',
    room_code text null,
    matched_player_id text null,
    created_at timestamptz not null default timezone('utc', now()),
    matched_at timestamptz null
);

create index if not exists idx_matchmaking_queue_status_created_at
    on public.matchmaking_queue (status, created_at);

create unique index if not exists uq_matchmaking_queue_waiting_player
    on public.matchmaking_queue (player_id)
    where status = 'waiting';
