create table if not exists public.rooms (
    id bigint generated by default as identity primary key,
    room_code text not null,
    session_name text not null,
    host_name text not null,
    player_count integer not null default 1,
    status text not null default 'waiting',
    created_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists uq_rooms_room_code
    on public.rooms (room_code);

create index if not exists idx_rooms_status_created_at
    on public.rooms (status, created_at);
