create table if not exists public.rooms (
    id bigint generated by default as identity primary key,
    room_code text not null,
    session_name text not null,
    host_name text not null,
    player_count integer not null default 1,
    status text not null default 'waiting',
    created_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists uq_rooms_room_code
    on public.rooms (room_code);

create index if not exists idx_rooms_status_created_at
    on public.rooms (status, created_at);

create table if not exists public.matchmaking_queue (
    id bigint generated by default as identity primary key,
    player_id text not null,
    status text not null default 'waiting',
    room_code text null,
    matched_player_id text null,
    created_at timestamptz not null default timezone('utc', now()),
    matched_at timestamptz null
);

create index if not exists idx_matchmaking_queue_status_created_at
    on public.matchmaking_queue (status, created_at);

create unique index if not exists uq_matchmaking_queue_waiting_player
    on public.matchmaking_queue (player_id)
    where status = 'waiting';
