create extension if not exists pgcrypto;

create table if not exists public.rooms (
    id bigint generated by default as identity primary key,
    room_code text not null,
    session_name text not null,
    host_name text not null,
    player_count integer not null default 1,
    status text not null default 'waiting',
    created_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists uq_rooms_room_code
    on public.rooms (room_code);

create index if not exists idx_rooms_status_created_at
    on public.rooms (status, created_at);

alter table public.rooms enable row level security;

drop policy if exists "rooms_select_all" on public.rooms;
create policy "rooms_select_all"
    on public.rooms
    for select
    to anon, authenticated
    using (true);

drop policy if exists "rooms_insert_all" on public.rooms;
create policy "rooms_insert_all"
    on public.rooms
    for insert
    to anon, authenticated
    with check (true);

drop policy if exists "rooms_update_all" on public.rooms;
create policy "rooms_update_all"
    on public.rooms
    for update
    to anon, authenticated
    using (true)
    with check (true);

create table if not exists public.matchmaking_queue (
    id uuid primary key default gen_random_uuid(),
    player_id text not null,
    status text not null default 'waiting',
    room_code text null,
    created_at timestamptz not null default timezone('utc', now()),
    matched_at timestamptz null
);

create index if not exists idx_matchmaking_queue_status_created_at
    on public.matchmaking_queue (status, created_at);

create unique index if not exists uq_matchmaking_queue_waiting_player
    on public.matchmaking_queue (player_id)
    where status = 'waiting';

alter table public.matchmaking_queue enable row level security;

drop policy if exists "matchmaking_queue_select_all" on public.matchmaking_queue;
create policy "matchmaking_queue_select_all"
    on public.matchmaking_queue
    for select
    to anon, authenticated
    using (true);

drop policy if exists "matchmaking_queue_insert_all" on public.matchmaking_queue;
create policy "matchmaking_queue_insert_all"
    on public.matchmaking_queue
    for insert
    to anon, authenticated
    with check (true);

drop policy if exists "matchmaking_queue_update_all" on public.matchmaking_queue;
create policy "matchmaking_queue_update_all"
    on public.matchmaking_queue
    for update
    to anon, authenticated
    using (true)
    with check (true);
